[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
log-db = False
syslog = False
log-level = info
admin_passwd = $pbkdf2-sha512$600000$/t87J8TYu/f.XwvBOKeUUg$W5Hdh4icKScwdz5m5OVDSXwsS3xMn1OtatHgZ7nXcVy3JUTiYLHuzUI7ZtEh/5fJhZi9XhK.99XGCefLBEETdA

